name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare for testing
      run: echo "This is a test file." > ${{github.workspace}}/build/test.txt

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Check code formatting
      run: |
        clang-format -i $(find ${{github.workspace}}/src -name "*.cpp") \
                        $(find ${{github.workspace}}/include -name "*.hpp") \
                        $(find ${{github.workspace}}/tests -name "*.cpp")
        if ! git diff --quiet; then
          echo "Code is not formatted. Please run clang-format before committing."
          exit 1
        fi
